Create database QUAN_LY_SIEU_THI_DIEN_MAY
go
use QUAN_LY_SIEU_THI_DIEN_MAY
go
 Create table KHACHHANG
 (
 IDKH char(10) not null primary key,
 MKH char(10) not null ,
 HOTENKH nvarchar(100) not null,
 DIACHIKH nvarchar(200) not null,
 SDTKH varchar(20),
 TONGTIENTIEUTHU money not null check (TONGTIENTIEUTHU > 0),
 TRANGTHAIKH nvarchar(50) not null,
 MOTAKH nvarchar(200),
 )
 go
  Create table QUYEN
 (
 IDQUYEN char(10) not null primary key,
 MAQUYEN char(10) not null ,
 TENQUYEN nvarchar(50) not null,
 TRANGTHAIQUYEN nvarchar(50) not null, 
 MOTAQUYEN nvarchar(200),
 )
 go
  Create table THONGSO
 (
 IDTS char(10) not null primary key,
 TENTS nvarchar(100) not null,
 )
 go
  Create table NHACUNGCAP
 (
 IDNCC char(10) not null primary key,
 MNCC char(10) not null ,
 TENNCC nvarchar(50) not null,
 SPCUNGCAP nvarchar(50) not null,
 DIACHINCC nvarchar(200) not null,
 SDTNCC varchar(50) not null,
 TRANGTHAINCC nvarchar(50) not null,
 MOTANCC nvarchar(200),
 )
 go 
  Create table NHASANXUAT
 (
 IDNSX char(10) not null primary key,
 MANSX char(10) not null ,
 TENNSX nvarchar(50) not null,
 DIACHINSX nvarchar(200) not null,
 SDTNSX varchar(20),
 TRANGTHAINSX nvarchar(50) not null,
 MOTANSX nvarchar(200),
 )
 go
  Create table LOAISANPHAM
 (
 IDLOAISP char(10) not null primary key,
 MLOAISP char(10) not null ,
 TENLOAI nvarchar(100) not null,
 TRANGTHAILOAISP nvarchar(50) not null,
 MOTALOAISP nvarchar(200),
 )
 go 



 
  Create table NGUOIDUNG
 (
 IDND char(10) not null primary key,
 MND char(10) not null ,
 TENND nvarchar(100) not null,
 IDQUYEN char(10) REFERENCES QUYEN(IDQUYEN),
 TKUSER varchar(20),
 PASSWORDUSER varchar(20),
 SDTND varchar(50),
 NGAYSINHND datetime not null,
 GIOITINHND nvarchar(50) not null,
 CTMNDND varchar(20) not null,
 TRINHDOHOCVANND nvarchar(50),
 QUEQUANND nvarchar(200),
 TRANGTHAIND nvarchar(50) not null,
 MOTAND nvarchar(200),
 )
 go
  Create table DATHANG
 (
 IDDH char(10) not null primary key,
 MDH char(10) not null ,
 IDKH char(10) not null REFERENCES KHACHHANG(IDKH),
 IDND char(10) not null REFERENCES NGUOIDUNG(IDND),
 NGAYDATHANG datetime default(getdate()),
 NGAYGIAOHANG datetime not null,
 TINHTRANGGIAOHANG nvarchar(50) not null,
 TRANGTHAIDH nvarchar(50) not null,
 MOTADH nvarchar(200),
 )
 go
 Create table HOADON
 (
 IDHD char(10) not null primary key,
 MHD char(10) not null ,
 IDKH char(10) not null REFERENCES KHACHHANG(IDKH),
 IDND char(10) not null REFERENCES NGUOIDUNG(IDND),
 NGAYLAPHD datetime default(getdate()),
 TRANGTHAIHD nvarchar(50) not null,
 MOTAHD nvarchar(200),
 )
 go


 Create table PHIEUNHAP
 (
 IDPHIEUNHAP char(10) not null primary key,
 MPN char(10) not null ,
 IDNCC char(10) not null REFERENCES NHACUNGCAP(IDNCC),
 IDND char(10) not null REFERENCES NGUOIDUNG(IDND),
 NGAYLAPPN datetime default(getdate()),
 TONGGIATRIPN money not null check(TONGGIATRIPN>0),
 TRANGTHAIPN nvarchar(50) not null,
 MOTAPN nvarchar(200),
 )
 go

 Create table SANPHAM
 (
 IDSP char(10) not null primary key,
 MSP char(10) not null ,
 IDLOAISP char(10) not null REFERENCES LOAISANPHAM(IDLOAISP),
 HINHANHSP image,
 IDNSX char(10) not null REFERENCES NHASANXUAT(IDNSX),
 TENSP nvarchar(100) not null,
 GIABANCU money not null check(GIABANCU>=0),
 GIABANMOI money not null check (GIABANMOI>=0),
 SOLUONG int not null check (SOLUONG>0),
 DONVITINH nvarchar(20) not null,
 TRANGTHAISP nvarchar(50) not null,
 GIOITHIEUSP nvarchar(50) not null,
 THOIGIANBAOHANH int not null,
 MOTASP nvarchar(200),
 )
 go 
  Create table CTDATHANG
(
 IDCTDH char(10) not null,
 IDDH char(10) not null REFERENCES DATHANG(IDDH),
 IDSP char(10) not null REFERENCES SANPHAM(IDSP),
 SOLUONGDH int not null check (SOLUONGDH>0),
 GIA money not null check(GIA>=0),
 Primary key (IDDH , IDSP , IDCTDH)
 )
 go

  Create table CTPHIEUNHAP
 (
 IDCTPN char(10) not null,
 IDPN char(10) not null REFERENCES PHIEUNHAP(IDPHIEUNHAP),
 IDSP char(10) not null REFERENCES SANPHAM(IDSP),
 GIA money not null check (GIA>=0),
 SOLUONGNHAP int not null check (SOLUONGNHAP >0),
 THANHTIEN money not null check (THANHTIEN>=0),
 Primary key (IDPN , IDSP , IDCTPN)
 )
 go
  Create table CTHOADON
 (
 IDCTHD char(10) not null,
 IDHD char(10) not null REFERENCES HOADON(IDHD),
 IDSP char(10) not null REFERENCES SANPHAM(IDSP),
 GIA money not null check (GIA>=0),
 SOLUONG int not null check (SOLUONG >0),
 Primary key (IDHD , IDSP , IDCTHD)
 )
 go
 Create table CTTHONGSO
 (
 IDCTTS char(10) not null,
 IDSP char(10) not null REFERENCES SANPHAM(IDSP),
 IDTS char(10) not null REFERENCES THONGSO(IDTS),
 GIATRITS nvarchar(50),
 Primary key (IDCTTS, IDSP, IDTS)
 )
 go
 --Thêm thủ tục
-- 1.thêm khách hàng
 create proc THEMKHACHHANG (@IDKH char(10),@MKH char(10),@HOTENKH nvarchar(100),@DIACHIKH nvarchar(200) ,@SDTKH varchar(20),@TONGTIENTIEUTHU money ,@TRANGTHAIKH nvarchar(50) , @MOTAKH nvarchar(200))
 as
 begin
 Insert into KHACHHANG(IDKH ,MKH ,HOTENKH ,DIACHIKH ,SDTKH ,TONGTIENTIEUTHU ,TRANGTHAIKH  ,MOTAKH)
 Values(@IDKH ,@MKH ,@HOTENKH ,@DIACHIKH ,@SDTKH ,@TONGTIENTIEUTHU ,@TRANGTHAIKH  ,@MOTAKH)
 END
 go
 Execute THEMKHACHHANG @IDKH='KH001',@MKH='001' ,@HOTENKH='Nguyễn Thành Hiệp' ,@DIACHIKH='HaNoi' ,@SDTKH='0123456789' ,@TONGTIENTIEUTHU='01123445',@TRANGTHAIKH='Tot'  ,@MOTAKH='Tot'
  Execute THEMKHACHHANG @IDKH='KH002' ,@MKH='002' ,@HOTENKH='Nguyễn Văn Hòa' ,@DIACHIKH='HaNoi' ,@SDTKH='0123456789' ,@TONGTIENTIEUTHU='01123445',@TRANGTHAIKH='Tot'  ,@MOTAKH='Tot'
   Execute THEMKHACHHANG @IDKH='KH003' ,@MKH='003' ,@HOTENKH='Vũ Long Khánh' ,@DIACHIKH='HaNoi' ,@SDTKH='0123456789' ,@TONGTIENTIEUTHU='01123445',@TRANGTHAIKH='Tot'  ,@MOTAKH='Tot'
    Execute THEMKHACHHANG @IDKH='KH004' ,@MKH='004' ,@HOTENKH='Lê Xuân Hoàng' ,@DIACHIKH='HaNoi' ,@SDTKH='0123456789' ,@TONGTIENTIEUTHU='01123445',@TRANGTHAIKH='Tot'  ,@MOTAKH='Tot'
     Execute THEMKHACHHANG @IDKH='KH005' ,@MKH='005' ,@HOTENKH='Nguyễn Phú Trọng' ,@DIACHIKH='HaNoi' ,@SDTKH='0123456789' ,@TONGTIENTIEUTHU='01123445',@TRANGTHAIKH='Tot'  ,@MOTAKH='Tot'
 go
 
 --2.thêm quyền
  create proc THEMQUYEN (@IDQUYEN char(10) ,@MAQUYEN char(10),@TENQUYEN nvarchar(50),@TRANGTHAIQUYEN nvarchar(50), @MOTAQUYEN nvarchar(200))
 AS
 BEGIN
 INSERT INTO QUYEN(IDQUYEN,MAQUYEN,TENQUYEN,TRANGTHAIQUYEN,MOTAQUYEN)
 VALUES(@IDQUYEN,@MAQUYEN,@TENQUYEN,@TRANGTHAIQUYEN,@MOTAQUYEN)
 END
 GO
 EXECUTE THEMQUYEN @IDQUYEN='Q001',@MAQUYEN='001',@TENQUYEN='Quản lý',@TRANGTHAIQUYEN='Tốt',@MOTAQUYEN='Quản lý nhân sự'
  EXECUTE THEMQUYEN @IDQUYEN='Q002',@MAQUYEN='002',@TENQUYEN='Nhân viên',@TRANGTHAIQUYEN='Tốt',@MOTAQUYEN='Nhân Viên Bán hàng'
   EXECUTE THEMQUYEN @IDQUYEN='Q003',@MAQUYEN='003',@TENQUYEN='Khách Hàng',@TRANGTHAIQUYEN='Tốt',@MOTAQUYEN='Khách hàng thân thiện'
   
go
--3.thêm thông số
create proc THEMTHONGSO ( @IDTS char(10),@TENTS nvarchar(100))
AS
BEGIN
INSERT INTO THONGSO(IDTS,TENTS)
VALUES (@IDTS,@TENTS)
END
GO
EXECUTE THEMTHONGSO @IDTS='TS001', @TENTS='Thông số abcdef'
EXECUTE THEMTHONGSO @IDTS='TS002', @TENTS='Thông số aadadasd'
EXECUTE THEMTHONGSO @IDTS='TS003', @TENTS='Thông số ádasdasd'
GO

--4.thêm nhà cung cấp
go
create proc THEMNHACUNGCAP (@IDNCC char(10),@MNCC char(10),@TENNCC nvarchar(50),@SPCUNGCAP nvarchar(50),@DIACHINCC nvarchar(200),@SDTNCC varchar(50),@TRANGTHAINCC nvarchar(50),@MOTANCC nvarchar(200))
as
begin
INSERT INTO  NHACUNGCAP(IDNCC ,MNCC ,TENNCC ,SPCUNGCAP,DIACHINCC,SDTNCC,TRANGTHAINCC,MOTANCC)
VALUES (@IDNCC ,@MNCC,@TENNCC,@SPCUNGCAP,@DIACHINCC ,@SDTNCC ,@TRANGTHAINCC,@MOTANCC )
END
go
EXECUTE THEMNHACUNGCAP @IDNCC='NCC001' ,@MNCC='001',@TENNCC='Văn Tiến Dũng',@SPCUNGCAP='heroin',@DIACHINCC ='Hà Nội',@SDTNCC ='0912456855',@TRANGTHAINCC='hdjashdkajshdkjau',@MOTANCC='ádjhasjhdkjashd' 
EXECUTE THEMNHACUNGCAP @IDNCC='NCC002' ,@MNCC='002',@TENNCC='Văn Tiến Dũng',@SPCUNGCAP='Cocain',@DIACHINCC ='Hà Nội',@SDTNCC ='0912456855',@TRANGTHAINCC='hdjashdkajshdkjau',@MOTANCC='ádjhasjhdkjashd' 
EXECUTE THEMNHACUNGCAP @IDNCC='NCC003' ,@MNCC='003',@TENNCC='Văn Tiến Dũng',@SPCUNGCAP='Cần xa',@DIACHINCC ='Hà Nội',@SDTNCC ='0912456855',@TRANGTHAINCC='hdjashdkajshdkjau',@MOTANCC='ádjhasjhdkjashd' 
EXECUTE THEMNHACUNGCAP @IDNCC='NCC004' ,@MNCC='004',@TENNCC='Văn Tiến Dũng',@SPCUNGCAP='ádas',@DIACHINCC ='Hà Nội',@SDTNCC ='0912456855',@TRANGTHAINCC='hdjashdkajshdkjau',@MOTANCC='ádjhasjhdkjashd' 
EXECUTE THEMNHACUNGCAP @IDNCC='NCC005' ,@MNCC='005',@TENNCC='Văn Tiến Dũng',@SPCUNGCAP='heroádasdin',@DIACHINCC ='Hà Nội',@SDTNCC ='0912456855',@TRANGTHAINCC='hdjashdkajshdkjau',@MOTANCC='ádjhasjhdkjashd' 
go
--5.thêm nhà sản xuất
 CREATE PROC THEMNHASANXUAT(@IDNSX char(10),@MANSX char(10) ,@TENNSX nvarchar(50) ,@DIACHINSX nvarchar(200) ,@SDTNSX varchar(20),@TRANGTHAINSX nvarchar(50) ,@MOTANSX nvarchar(200))
AS
BEGIN
	Insert into NHASANXUAT(IDNSX, MANSX, TENNSX, DIACHINSX, SDTNSX,TRANGTHAINSX,MOTANSX)
	Values ( @IDNSX, @MANSX, @TENNSX, @DIACHINSX, @SDTNSX,@TRANGTHAINSX,@MOTANSX)
END
go
execute THEMNHASANXUAT @IDNSX='NSX001', @MANSX='001', @TENNSX='a', @DIACHINSX='aaaa', @SDTNSX='013213',@TRANGTHAINSX='aaa',@MOTANSX='aaaa'
execute THEMNHASANXUAT @IDNSX='NSX002', @MANSX='002', @TENNSX='b', @DIACHINSX='aaaa', @SDTNSX='013213',@TRANGTHAINSX='aaa',@MOTANSX='aaaa'
execute THEMNHASANXUAT @IDNSX='NSX003', @MANSX='003', @TENNSX='c', @DIACHINSX='aaaa', @SDTNSX='013213',@TRANGTHAINSX='aaa',@MOTANSX='aaaa'
execute THEMNHASANXUAT @IDNSX='NSX004', @MANSX='004', @TENNSX='d', @DIACHINSX='aaaa', @SDTNSX='013213',@TRANGTHAINSX='aaa',@MOTANSX='aaaa'
execute THEMNHASANXUAT @IDNSX='NSX005', @MANSX='005', @TENNSX='e', @DIACHINSX='aaaa', @SDTNSX='013213',@TRANGTHAINSX='aaa',@MOTANSX='aaaa'
go

--6.thêm loại sản phẩm
 CREATE PROC THEMLOAISANPHAM(@IDLOAISP char(10),@MLOAISP char(10),@TENLOAI nvarchar(100),@TRANGTHAILOAISP nvarchar(50),@MOTALOAISP nvarchar(200))
AS
BEGIN
	Insert into LOAISANPHAM(IDLOAISP, MLOAISP, TENLOAI, TRANGTHAILOAISP, MOTALOAISP)
	Values ( @IDLOAISP, @MLOAISP, @TENLOAI, @TRANGTHAILOAISP, @MOTALOAISP)
END
go
execute THEMLOAISANPHAM @IDLOAISP='LSP001', @MLOAISP='001', @TENLOAI='a',@TRANGTHAILOAISP='aaa',@MOTALOAISP='aaaa'
execute THEMLOAISANPHAM @IDLOAISP='LSP002', @MLOAISP='002', @TENLOAI='b',@TRANGTHAILOAISP='aaa',@MOTALOAISP='aaaa'
execute THEMLOAISANPHAM @IDLOAISP='LSP003', @MLOAISP='003', @TENLOAI='c',@TRANGTHAILOAISP='aaa',@MOTALOAISP='aaaa'
execute THEMLOAISANPHAM @IDLOAISP='LSP004', @MLOAISP='004', @TENLOAI='d',@TRANGTHAILOAISP='aaa',@MOTALOAISP='aaaa'
execute THEMLOAISANPHAM @IDLOAISP='LSP005', @MLOAISP='005', @TENLOAI='ae',@TRANGTHAILOAISP='aaa',@MOTALOAISP='aaaa'
go


--7.thêm người dùng
 CREATE PROC THEMNGUOIDUNG( @IDND char(10) ,@MND char(10) ,@TENND nvarchar(100),@IDQUYEN char(10) ,@TKUSER varchar(20),@PASSWORDUSER varchar(20),@SDTND varchar(50),@NGAYSINHND datetime,@GIOITINHND nvarchar(50),@CTMNDND varchar(20),@TRINHDOHOCVANND nvarchar(50),@QUEQUANND nvarchar(200),@TRANGTHAIND nvarchar(50),@MOTAND nvarchar(200))
AS
BEGIN
	Insert into NGUOIDUNG(IDND ,MND ,TENND ,IDQUYEN ,TKUSER,PASSWORDUSER,SDTND,NGAYSINHND,GIOITINHND,CTMNDND,TRINHDOHOCVANND,QUEQUANND,TRANGTHAIND,MOTAND)
	Values ( @IDND ,@MND ,@TENND ,@IDQUYEN ,@TKUSER,@PASSWORDUSER,@SDTND,@NGAYSINHND,@GIOITINHND,@CTMNDND,@TRINHDOHOCVANND,@QUEQUANND,@TRANGTHAIND,@MOTAND)
END
go
execute THEMNGUOIDUNG @IDND='ND001', @MND='001', @TENND='a',@IDQUYEN='Q001',@TKUSER='user',@PASSWORDUSER='user',@SDTND='0123456789',@NGAYSINHND='1997/01/01',@GIOITINHND=N'Nam',@CTMNDND='012134',@TRINHDOHOCVANND='12/12',@QUEQUANND=N'Nam Định',@TRANGTHAIND='aaaa',@MOTAND='aaaa'
execute THEMNGUOIDUNG @IDND='ND002', @MND='002', @TENND='a',@IDQUYEN='Q002',@TKUSER='nv',@PASSWORDUSER='nv',@SDTND='0123456789',@NGAYSINHND='1997/01/01',@GIOITINHND=N'Nam',@CTMNDND='012134',@TRINHDOHOCVANND='12/12',@QUEQUANND=N'Nam Định',@TRANGTHAIND='aaaa',@MOTAND='aaaa'
execute THEMNGUOIDUNG @IDND='ND003', @MND='003', @TENND='a',@IDQUYEN='Q003',@TKUSER='kh',@PASSWORDUSER='kh',@SDTND='0123456789',@NGAYSINHND='1997/01/01',@GIOITINHND=N'Nam',@CTMNDND='012134',@TRINHDOHOCVANND='12/12',@QUEQUANND=N'Nam Định',@TRANGTHAIND='aaaa',@MOTAND='aaaa'
execute THEMNGUOIDUNG @IDND='ND004', @MND='004', @TENND='a',@IDQUYEN='Q001',@TKUSER='user',@PASSWORDUSER='user',@SDTND='0123456789',@NGAYSINHND='1997/01/01',@GIOITINHND=N'Nam',@CTMNDND='012134',@TRINHDOHOCVANND='12/12',@QUEQUANND=N'Nam Định',@TRANGTHAIND='aaaa',@MOTAND='aaaa'
execute THEMNGUOIDUNG @IDND='ND005', @MND='005', @TENND='a',@IDQUYEN='Q002',@TKUSER='nv',@PASSWORDUSER='nv',@SDTND='0123456789',@NGAYSINHND='1997/01/01',@GIOITINHND=N'Nam',@CTMNDND='012134',@TRINHDOHOCVANND='12/12',@QUEQUANND=N'Nam Định',@TRANGTHAIND='aaaa',@MOTAND='aaaa'

go

--8.thêm đặt hàng
 CREATE PROC THEMDATHANG( @IDDH char(10) ,@MDH char(10) ,@IDKH char(10) ,@IDND char(10) ,@NGAYDATHANG datetime ,@NGAYGIAOHANG datetime ,@TINHTRANGGIAOHANG nvarchar(50) ,@TRANGTHAIDH nvarchar(50) ,@MOTADH nvarchar(200))
AS
BEGIN
	Insert into DATHANG(IDDH,MDH,IDKH,IDND,NGAYDATHANG,NGAYGIAOHANG,TINHTRANGGIAOHANG,TRANGTHAIDH,MOTADH)
	Values ( @IDDH,@MDH,@IDKH,@IDND,@NGAYDATHANG,@NGAYGIAOHANG,@TINHTRANGGIAOHANG,@TRANGTHAIDH,@MOTADH)
END
go
execute THEMDATHANG @IDDH='DH001',@MDH='001',@IDKH='KH001',@IDND='ND001',@NGAYDATHANG='2018/01/01',@NGAYGIAOHANG='2018/01/05',@TINHTRANGGIAOHANG=N'Đã giao',@TRANGTHAIDH='aaa',@MOTADH='aaaa'
execute THEMDATHANG @IDDH='DH002',@MDH='002',@IDKH='KH002',@IDND='ND002',@NGAYDATHANG='2018/01/01',@NGAYGIAOHANG='2018/01/05',@TINHTRANGGIAOHANG=N'Đã giao',@TRANGTHAIDH='aaa',@MOTADH='aaaa'
execute THEMDATHANG @IDDH='DH003',@MDH='003',@IDKH='KH003',@IDND='ND003',@NGAYDATHANG='2018/01/01',@NGAYGIAOHANG='2018/01/05',@TINHTRANGGIAOHANG=N'Đã giao',@TRANGTHAIDH='aaa',@MOTADH='aaaa'
execute THEMDATHANG @IDDH='DH004',@MDH='004',@IDKH='KH004',@IDND='ND004',@NGAYDATHANG='2018/01/01',@NGAYGIAOHANG='2018/01/05',@TINHTRANGGIAOHANG=N'Đã giao',@TRANGTHAIDH='aaa',@MOTADH='aaaa'
execute THEMDATHANG @IDDH='DH005',@MDH='005',@IDKH='KH005',@IDND='ND005',@NGAYDATHANG='2018/01/01',@NGAYGIAOHANG='2018/01/05',@TINHTRANGGIAOHANG=N'Đã giao',@TRANGTHAIDH='aaa',@MOTADH='aaaa'

go

--9.thêm hóa đơn
GO
create proc THEMHOADON (@IDHD char(10), @MHD char(10), @IDKH char(10), @IDND char(10), @NGAYLAPHD datetime, @TRANGTHAIHD nvarchar(50), @MOTAHD nvarchar(200))
AS
BEGIN
	INSERT INTO HOADON(IDHD, MHD, IDKH, IDND, NGAYLAPHD, TRANGTHAIHD, MOTAHD)
	VALUES (@IDHD, @MHD, @IDKH, @IDND, @NGAYLAPHD, @TRANGTHAIHD, @MOTAHD)
END

GO
EXECUTE THEMHOADON @IDHD='HD001', @MHD='001',@IDKH='KH001', @IDND='ND001',@NGAYLAPHD='2018-1-1', @TRANGTHAIHD=N'Có', @MOTAHD=N'Đã thanh toán'
EXECUTE THEMHOADON @IDHD='HD002', @MHD='001',@IDKH='KH001', @IDND='ND001',@NGAYLAPHD='2018-1-1', @TRANGTHAIHD=N'Có', @MOTAHD=N'Đã thanh toán'
EXECUTE THEMHOADON @IDHD='HD003', @MHD='001',@IDKH='KH001', @IDND='ND001',@NGAYLAPHD='2018-1-1', @TRANGTHAIHD=N'Có', @MOTAHD=N'Đã thanh toán'
EXECUTE THEMHOADON @IDHD='HD004', @MHD='001',@IDKH='KH001', @IDND='ND001',@NGAYLAPHD='2018-1-1', @TRANGTHAIHD=N'Có', @MOTAHD=N'Đã thanh toán'
EXECUTE THEMHOADON @IDHD='HD005', @MHD='001',@IDKH='KH001', @IDND='ND001',@NGAYLAPHD='2018-1-1', @TRANGTHAIHD=N'Có', @MOTAHD=N'Đã thanh toán'
GO

--10.thêm phiếu nhập
CREATE PROC THEMPHIEUNHAP(@IDPHIEUNHAP CHAR(10), @MPN CHAR(10), @IDNCC CHAR(10),@IDND char(10), @NGAYLAPPN datetime, @TONGGIATRIPN money, @TRANGTHAIPN nvarchar(50),@MOTAPN nvarchar(200))
AS
BEGIN
	Insert into PHIEUNHAP(IDPHIEUNHAP, MPN, IDNCC,IDND, NGAYLAPPN, TONGGIATRIPN, TRANGTHAIPN,MOTAPN)
	Values (@IDPHIEUNHAP,  @MPN, @IDNCC,@IDND, @NGAYLAPPN, @TONGGIATRIPN, @TRANGTHAIPN,@MOTAPN)
END
go
execute THEMPHIEUNHAP @IDPHIEUNHAP='PN001',  @MPN='001', @IDNCC='NCC001', @IDND='ND001', @NGAYLAPPN='2018-1-1', @TONGGIATRIPN='200000', @TRANGTHAIPN=N'có',@MOTAPN=N'??y ??'
execute THEMPHIEUNHAP @IDPHIEUNHAP='PN002',  @MPN='002', @IDNCC='NCC002', @IDND='ND002', @NGAYLAPPN='2018-1-2', @TONGGIATRIPN='200000', @TRANGTHAIPN=N'có',@MOTAPN=N'??y ??'
execute THEMPHIEUNHAP @IDPHIEUNHAP='PN003',  @MPN='003', @IDNCC='NCC003', @IDND='ND003', @NGAYLAPPN='2018-1-3', @TONGGIATRIPN='200000', @TRANGTHAIPN=N'không',@MOTAPN=N'??y ??'
execute THEMPHIEUNHAP @IDPHIEUNHAP='PN004',  @MPN='004', @IDNCC='NCC004', @IDND='ND001', @NGAYLAPPN='2018-1-4', @TONGGIATRIPN='200000', @TRANGTHAIPN=N'có',@MOTAPN=N'thi?u hàng'
execute THEMPHIEUNHAP @IDPHIEUNHAP='PN005',  @MPN='005', @IDNCC='NCC005', @IDND='ND002', @NGAYLAPPN='2018-1-5', @TONGGIATRIPN='200000', @TRANGTHAIPN=N'không',@MOTAPN=N'??y ??'
go
--11.thêm sản phẩm
CREATE PROC THEMSAMPHAM(@IDSP CHAR(10), @MSP CHAR(10), @IDLOAISP CHAR(10), @HINHANHSP IMAGE, @IDNSX CHAR(10), @TENSP nvarchar(100),@GIABANCU  money,@GIABANMOI money,@SOLUONG INT,@DONVITINH nvarchar(20),@TRANGTHAISP nvarchar(20),@GIOITHIEUSP nvarchar(50),@THOIGIANBAOHANH int,@MOTASP nvarchar(200))
AS
BEGIN
	Insert into SANPHAM(IDSP , MSP , IDLOAISP , HINHANHSP , IDNSX, TENSP,GIABANCU,GIABANMOI,SOLUONG,DONVITINH,TRANGTHAISP,GIOITHIEUSP,THOIGIANBAOHANH,MOTASP)
	Values (@IDSP , @MSP , @IDLOAISP , @HINHANHSP , @IDNSX, @TENSP,@GIABANCU,@GIABANMOI,@SOLUONG,@DONVITINH,@TRANGTHAISP,@GIOITHIEUSP,@THOIGIANBAOHANH,@MOTASP)

END
GO
execute THEMSAMPHAM @IDSP='SP001', @MSP='001', @IDLOAISP='LSP001', @HINHANHSP='', @IDNSX='NSX001', @TENSP='ABC', @GIABANCU='2000000', @GIABANMOI='1500000', @SOLUONG='50', @DONVITINH=N'VND', @TRANGTHAISP=N'BÁN CHẠY',@GIOITHIEUSP=N'aa', @THOIGIANBAOHANH='5', @MOTASP=N'kHÁ B?T M?T'
execute THEMSAMPHAM @IDSP='SP002', @MSP='002', @IDLOAISP='LSP002', @HINHANHSP='', @IDNSX='NSX002', @TENSP='ABC', @GIABANCU='3000000', @GIABANMOI='2500000', @SOLUONG='50', @DONVITINH=N'VND', @TRANGTHAISP=N'BÁN CHẠY',@GIOITHIEUSP=N'CÁ TÍNH', @THOIGIANBAOHANH='5', @MOTASP=N'kHÁ B?T M?T'
execute THEMSAMPHAM @IDSP='SP003', @MSP='003', @IDLOAISP='LSP003', @HINHANHSP='', @IDNSX='NSX003', @TENSP='ABC', @GIABANCU='4000000', @GIABANMOI='3500000', @SOLUONG='50', @DONVITINH=N'VND', @TRANGTHAISP=N'BÁN CHẠY',@GIOITHIEUSP=N'CÁ TÍNH', @THOIGIANBAOHANH='5', @MOTASP=N'kHÁ B?T M?T'
execute THEMSAMPHAM @IDSP='SP004', @MSP='004', @IDLOAISP='LSP004', @HINHANHSP='', @IDNSX='NSX004', @TENSP='ABC', @GIABANCU='5000000', @GIABANMOI='4500000', @SOLUONG='50', @DONVITINH=N'VND', @TRANGTHAISP=N'BÁN CHẠY',@GIOITHIEUSP=N'CÁ TÍNH', @THOIGIANBAOHANH='5', @MOTASP=N'kHÁ B?T M?T'
execute THEMSAMPHAM @IDSP='SP005', @MSP='005', @IDLOAISP='LSP005', @HINHANHSP='', @IDNSX='NSX005', @TENSP='ABC', @GIABANCU='6000000', @GIABANMOI='5500000', @SOLUONG='50', @DONVITINH=N'VND', @TRANGTHAISP=N'BÁN CHẠY',@GIOITHIEUSP=N'CÁ TÍNH', @THOIGIANBAOHANH='5', @MOTASP=N'kHÁ B?T M?T'
GO
--12.thêm chi tiết đặt hàng
CREATE PROC THEMCTDATHANG(@IDCTDH CHAR(10), @IDDH CHAR(10), @IDSP CHAR(10), @SOLUONGDH int, @GIA money)
AS
BEGIN
	Insert into CTDATHANG(IDCTDH, IDDH, IDSP, SOLUONGDH,GIA)
	Values (@IDCTDH,  @IDDH, @IDSP, @SOLUONGDH,@GIA)
END
GO
execute THEMCTDATHANG @IDCTDH='CTDH001',  @IDDH='DH001', @IDSP='SP001', @SOLUONGDH='50' , @GIA ='100000'
execute THEMCTDATHANG @IDCTDH='CTDH002',  @IDDH='DH002', @IDSP='SP002', @SOLUONGDH='50', @GIA ='100000'
execute THEMCTDATHANG @IDCTDH='CTDH003',  @IDDH='DH003', @IDSP='SP003', @SOLUONGDH='50', @GIA ='100000'
execute THEMCTDATHANG @IDCTDH='CTDH004',  @IDDH='DH004', @IDSP='SP004', @SOLUONGDH='50', @GIA ='100000'
execute THEMCTDATHANG @IDCTDH='CTDH005',  @IDDH='DH005', @IDSP='SP005', @SOLUONGDH='50', @GIA ='100000'
GO

--13.thêm ct phiếu nhập
GO
create proc THEMCTPHIEUNHAP (@IDCTPN char(10), @IDPN char(10), @IDSP char(10), @GIA money, @SOLUONGNHAP int, @THANHTIEN money)
AS
BEGIN
	INSERT INTO CTPHIEUNHAP(IDCTPN, IDPN, IDSP, GIA, SOLUONGNHAP, THANHTIEN)
	VALUES (@IDCTPN, @IDPN, @IDSP, @GIA, @SOLUONGNHAP, @THANHTIEN)
END

GO
EXECUTE THEMCTPHIEUNHAP @IDCTPN='CTPN001', @IDPN='PN001', @IDSP='SP001', @GIA='10000000', @SOLUONGNHAP='100', @THANHTIEN='1000000000'
EXECUTE THEMCTPHIEUNHAP @IDCTPN='CTPN002', @IDPN='PN001', @IDSP='SP002', @GIA='10000000', @SOLUONGNHAP='100', @THANHTIEN='1000000000'
EXECUTE THEMCTPHIEUNHAP @IDCTPN='CTPN003', @IDPN='PN001', @IDSP='SP003', @GIA='10000000', @SOLUONGNHAP='100', @THANHTIEN='1000000000'
EXECUTE THEMCTPHIEUNHAP @IDCTPN='CTPN004', @IDPN='PN001', @IDSP='SP004', @GIA='10000000', @SOLUONGNHAP='100', @THANHTIEN='1000000000'
EXECUTE THEMCTPHIEUNHAP @IDCTPN='CTPN005', @IDPN='PN001', @IDSP='SP005', @GIA='10000000', @SOLUONGNHAP='100', @THANHTIEN='1000000000'
GO

--14. thêm ct hóa đơn
GO
create proc THEMCTHOADON (@IDCTHD char(10), @IDHD char(10), @IDSP char(10), @GIA money, @SOLUONG int)
AS
BEGIN
	INSERT INTO CTHOADON(IDCTHD, IDHD, IDSP, GIA, SOLUONG)
	VALUES (@IDCTHD, @IDHD, @IDSP, @GIA, @SOLUONG)
END

GO
EXECUTE THEMCTHOADON @IDCTHD='CTHD001', @IDHD='HD001', @IDSP='SP001', @GIA='1000000', @SOLUONG='100'
EXECUTE THEMCTHOADON @IDCTHD='CTHD002', @IDHD='HD001', @IDSP='SP001', @GIA='1000000', @SOLUONG='100'
EXECUTE THEMCTHOADON @IDCTHD='CTHD003', @IDHD='HD001', @IDSP='SP001', @GIA='1000000', @SOLUONG='100'
EXECUTE THEMCTHOADON @IDCTHD='CTHD004', @IDHD='HD001', @IDSP='SP001', @GIA='1000000', @SOLUONG='100'
EXECUTE THEMCTHOADON @IDCTHD='CTHD005', @IDHD='HD001', @IDSP='SP001', @GIA='1000000', @SOLUONG='100'
GO

-- 15. thêm ct thông số
GO
create proc THEMCTTHONGSO (@IDCTTS char(10), @IDSP char(10), @IDTS char(10), @GIATRITS nvarchar(50))
AS
BEGIN
	INSERT INTO CTTHONGSO(IDCTTS, IDSP, IDTS, GIATRITS)
	VALUES (@IDCTTS, @IDSP, @IDTS, @GIATRITS)
END

GO
EXECUTE THEMCTTHONGSO @IDCTTS='CTTS001', @IDSP='SP001', @IDTS='TS001', @GIATRITS=N'thông số này không có giá trị gì'
EXECUTE THEMCTTHONGSO @IDCTTS='CTTS002', @IDSP='SP001', @IDTS='TS001', @GIATRITS=N'thông số này không có giá trị gì'
EXECUTE THEMCTTHONGSO @IDCTTS='CTTS003', @IDSP='SP001', @IDTS='TS001', @GIATRITS=N'thông số này không có giá trị gì'
EXECUTE THEMCTTHONGSO @IDCTTS='CTTS004', @IDSP='SP001', @IDTS='TS001', @GIATRITS=N'thông số này không có giá trị gì'
EXECUTE THEMCTTHONGSO @IDCTTS='CTTS005', @IDSP='SP001', @IDTS='TS001', @GIATRITS=N'thông số này không có giá trị gì'
GO

-- thủ tục sửa

--1.sửa khách hàng

CREATE PROC SUAKHACHHANG (@IDKH char(10),@MKH char(10),@HOTENKH nvarchar(100),@DIACHIKH nvarchar(200) ,@SDTKH varchar(20),@TONGTIENTIEUTHU money ,@TRANGTHAIKH nvarchar(50) , @MOTAKH nvarchar(200))
AS
BEGIN
   UPDATE KHACHHANG
   SET MKH=@MKH,HOTENKH=@HOTENKH,DIACHIKH=@DIACHIKH ,SDTKH=@SDTKH,TONGTIENTIEUTHU=@TONGTIENTIEUTHU ,TRANGTHAIKH=@TRANGTHAIKH, MOTAKH=@MOTAKH
   WHERE IDKH=@IDKH
   END
GO
execute SUAKHACHHANG @IDKH='KH005' ,@MKH='005' ,@HOTENKH='Nguyễn Phú Trọng' ,@DIACHIKH='Nam Dinh' ,@SDTKH='0123456789' ,@TONGTIENTIEUTHU='01123445',@TRANGTHAIKH='Tot'  ,@MOTAKH='Tot'
go
--2.sửa quyền
CREATE PROC SUAQUYEN(@IDQUYEN char(10) ,@MAQUYEN char(10),@TENQUYEN nvarchar(50),@TRANGTHAIQUYEN nvarchar(50), @MOTAQUYEN nvarchar(200))
AS
BEGIN
      UPDATE QUYEN
      SET MAQUYEN=@MAQUYEN ,TENQUYEN=@TENQUYEN,TRANGTHAIQUYEN=@TRANGTHAIQUYEN , MOTAQUYEN=@MOTAQUYEN
      WHERE IDQUYEN=@IDQUYEN 
      END
      GO
EXECUTE SUAQUYEN @IDQUYEN='Q003',@MAQUYEN='003',@TENQUYEN='Khách Hàng',@TRANGTHAIQUYEN=N'Tốt',@MOTAQUYEN='Khách hàng'
go
--3. sửa thông số
GO
CREATE PROC SUATHONGSO( @IDTS char(10),@TENTS nvarchar(100))
AS
BEGIN
UPDATE THONGSO
SET  TENTS=@TENTS
WHERE IDTS=@IDTS
END

GO
EXECUTE SUATHONGSO @IDTS='TS003', @TENTS='Thông số c'
go
--4.sửa nhà cung cấp
CREATE PROC SUANHACUNGCAP (@IDNCC char(10),@MNCC char(10),@TENNCC nvarchar(50),@SPCUNGCAP nvarchar(50),@DIACHINCC nvarchar(200),@SDTNCC varchar(50),@TRANGTHAINCC nvarchar(50),@MOTANCC nvarchar(200))
AS
BEGIN
UPDATE NHACUNGCAP
SET  MNCC=@MNCC ,TENNCC=@TENNCC ,SPCUNGCAP=@SPCUNGCAP,DIACHINCC=@DIACHINCC,SDTNCC=@SDTNCC,TRANGTHAINCC=@TRANGTHAINCC,MOTANCC=@MOTANCC
WHERE IDNCC=@IDNCC
END
go
EXECUTE SUANHACUNGCAP @IDNCC='NCC005' ,@MNCC='005',@TENNCC='Văn Tiến Dũng',@SPCUNGCAP='a',@DIACHINCC ='Hà Nội',@SDTNCC ='0912456855',@TRANGTHAINCC='hdjashdkajshdkjau',@MOTANCC='ádjhasjhdkjashd' 
go
--5. sửa nhà sản xuất
CREATE PROC SUANHASANXUAT(@IDNSX char(10),@MANSX char(10) ,@TENNSX nvarchar(50) ,@DIACHINSX nvarchar(200) ,@SDTNSX varchar(20),@TRANGTHAINSX nvarchar(50) ,@MOTANSX nvarchar(200))
AS
BEGIN
	Update NHASANXUAT
	set  MANSX=@MANSX, TENNSX=@TENNSX, DIACHINSX=@DIACHINSX, SDTNSX=@SDTNSX,TRANGTHAINSX=@TRANGTHAINSX,MOTANSX=@MOTANSX
	Where IDNSX=@IDNSX
END
go
execute SUANHASANXUAT @IDNSX='NSX001', @MANSX='002', @TENNSX='a', @DIACHINSX='aaaa', @SDTNSX='013213',@TRANGTHAINSX='aaa',@MOTANSX='aaba'

go

--6. sửa loại sản phẩm
CREATE PROC SUALOAISANPHAM(@IDLOAISP char(10),@MLOAISP char(10),@TENLOAI nvarchar(100),@TRANGTHAILOAISP nvarchar(50),@MOTALOAISP nvarchar(200))
AS
BEGIN
	Update LOAISANPHAM
	set  MLOAISP=@MLOAISP, TENLOAI=@TENLOAI,TRANGTHAILOAISP=@TRANGTHAILOAISP,MOTALOAISP=@MOTALOAISP
	Where IDLOAISP=@IDLOAISP
END
go
execute SUALOAISANPHAM @IDLOAISP='NSX001', @MLOAISP='002', @TENLOAI='a',@TRANGTHAILOAISP='aaa',@MOTALOAISP='aaba'
go
--7. sửa người dùng
CREATE PROC SUANGUOIDUNG(@IDND char(10) ,@MND char(10) ,@TENND nvarchar(100),@IDQUYEN char(10) ,@TKUSER varchar(20),@PASSWORDUSER varchar(20),@SDTND varchar(50),@NGAYSINHND datetime,@GIOITINHND nvarchar(50),@CTMNDND varchar(20),@TRINHDOHOCVANND nvarchar(50),@QUEQUANND nvarchar(200),@TRANGTHAIND nvarchar(50),@MOTAND nvarchar(200))
AS
BEGIN
	Update NGUOIDUNG
	set  MND=@MND ,TENND=@TENND ,IDQUYEN=@IDQUYEN ,TKUSER=@TKUSER,PASSWORDUSER=@PASSWORDUSER,SDTND=@SDTND,NGAYSINHND=@NGAYSINHND,GIOITINHND=@GIOITINHND,CTMNDND=@CTMNDND,TRINHDOHOCVANND=@TRINHDOHOCVANND,QUEQUANND=@QUEQUANND,TRANGTHAIND=@TRANGTHAIND,MOTAND=@MOTAND
	Where IDND=@IDND
END
go
execute SUANGUOIDUNG @IDND='ND001', @MND='001', @TENND='bbb',@IDQUYEN='Q001',@TKUSER='user',@PASSWORDUSER='user',@SDTND='0123456789',@NGAYSINHND='1997/01/01',@GIOITINHND=N'Nam',@CTMNDND='012134',@TRINHDOHOCVANND='12/12',@QUEQUANND=N'Nam Định',@TRANGTHAIND='aaaa',@MOTAND='aaaa'
go


--8. sửa đặt hàng

CREATE PROC SUADATHANG(@IDDH char(10) ,@MDH char(10) ,@IDKH char(10) ,@IDND char(10) ,@NGAYDATHANG datetime ,@NGAYGIAOHANG datetime ,@TINHTRANGGIAOHANG nvarchar(50) ,@TRANGTHAIDH nvarchar(50) ,@MOTADH nvarchar(200))
AS
BEGIN
	Update DATHANG
	set  MDH=@MDH ,IDKH=@IDKH ,IDND=@IDND ,NGAYDATHANG=@NGAYDATHANG,NGAYGIAOHANG=@NGAYGIAOHANG,TINHTRANGGIAOHANG=@TINHTRANGGIAOHANG,TRANGTHAIDH=@TRANGTHAIDH,MOTADH=@MOTADH
	Where IDDH=@IDDH
END
go
execute SUADATHANG @IDDH='DH001',@MDH='001',@IDKH='KH001',@IDND='ND001',@NGAYDATHANG='2018/01/01',@NGAYGIAOHANG='2018/01/05',@TINHTRANGGIAOHANG=N'Đã giao',@TRANGTHAIDH='abba',@MOTADH='aaaa'
go
--9. sửa hóa đơn

CREATE PROC SUAHOADON (@IDHD char(10), @MHD char(10), @IDKH char(10), @IDND char(10), @NGAYLAPHD datetime, @TRANGTHAIHD nvarchar(50), @MOTAHD nvarchar(200))
AS
BEGIN
	UPDATE HOADON
	SET	MHD = @MHD, IDKH = @IDKH, IDND = @IDND, NGAYLAPHD = @NGAYLAPHD, TRANGTHAIHD = @TRANGTHAIHD, MOTAHD = @MOTAHD
	WHERE IDHD = @IDHD
END

GO
EXECUTE SUAHOADON @IDHD='HD001', @MHD='002',@IDKH='KH002', @IDND='ND002',@NGAYLAPHD='2018-1-2', @TRANGTHAIHD=N'Có', @MOTAHD=N'Chưa thanh toán'
GO
--10.sửa phiếu nhập
go
CREATE PROC SUAPHIEUNHAP(@IDPHIEUNHAP CHAR(10), @MPN CHAR(10), @IDNCC CHAR(10), @NGAYLAPPN datetime, @TONGGIATRIPN money, @TRANGTHAIPN nvarchar(50),@MOTAPN nvarchar(200))
AS
BEGIN
	Update PHIEUNHAP
	set   MPN= @MPN, IDNCC = @IDNCC, NGAYLAPPN = @NGAYLAPPN, TONGGIATRIPN = @TONGGIATRIPN, TRANGTHAIPN=@TRANGTHAIPN,MOTAPN=@MOTAPN
	Where IDPHIEUNHAP= @IDPHIEUNHAP
END
execute SUAPHIEUNHAP @IDPHIEUNHAP='PN005',  @MPN='005', @IDNCC='NCC005', @NGAYLAPPN='2018-1-5', @TONGGIATRIPN='100000', @TRANGTHAIPN=N'không',@MOTAPN=N'??y ??'

--11.sửa sản phẩm
GO
CREATE PROC SUASANPHAM(@IDSP CHAR(10), @MSP CHAR(10), @IDLOAISP CHAR(10), @HINHANHSP IMAGE, @IDNSX CHAR(10), @TENSP nvarchar(100),@GIABANCU  money,@GIABANMOI money,@SOLUONG INT,@DONVITINH nvarchar(20),@TRANGTHAISP nvarchar(20),@GIOITHIEUSP nvarchar(50),@THOIGIANBAOHANH int ,@MOTASP nvarchar(200))
AS
BEGIN
	Update SANPHAM
	set   MSP = @MSP, IDLOAISP = @IDLOAISP, HINHANHSP = @HINHANHSP,IDNSX=@IDNSX,TENSP=@TENSP,GIABANCU=@GIABANCU,GIABANMOI=@GIABANMOI,SOLUONG=@SOLUONG,DONVITINH=@DONVITINH,TRANGTHAISP=@TRANGTHAISP,GIOITHIEUSP=@GIOITHIEUSP,THOIGIANBAOHANH=@THOIGIANBAOHANH,MOTASP=@MOTASP
	Where IDSP= @IDSP
END
execute SUASANPHAM @IDSP='SP005', @MSP='005', @IDLOAISP='LSP005', @HINHANHSP='', @IDNSX='NSX005', @TENSP='ABCD', @GIABANCU='6000000', @GIABANMOI='5500000', @SOLUONG='50', @DONVITINH=N'VND', @TRANGTHAISP=N'BÁN CHẠY',@GIOITHIEUSP=N'CÁ TÍNH', @THOIGIANBAOHANH='5', @MOTASP=N'kHÁ B?T M?T'
go
--12.sửa ct đặt hàng
go
CREATE PROC SUACTDATHANG(@IDCTDH CHAR(10), @IDDH CHAR(10), @IDSP CHAR(10), @SOLUONGDH int, @GIA money)
AS
BEGIN
	Update CTDATHANG
	set   IDDH= @IDDH, IDSP = @IDSP, SOLUONGDH = @SOLUONGDH, GIA = @GIA
	Where IDCTDH= @IDCTDH
END
go
execute SUACTDATHANG @IDCTDH='CTDH005',  @IDDH='DH005', @IDSP='SP005', @SOLUONGDH='500', @GIA ='100000'
go
-- 13. sửa ct phiếu nhập
GO 
CREATE PROC SUACTPHIEUNHAP (@IDCTPN char(10), @IDPN char(10), @IDSP char(10), @GIA money, @SOLUONGNHAP int, @THANHTIEN money)
AS
BEGIN
	UPDATE CTPHIEUNHAP
	SET	IDPN = @IDPN, IDSP = @IDSP, GIA = @GIA, SOLUONGNHAP = @SOLUONGNHAP, THANHTIEN = @THANHTIEN
	WHERE IDCTPN = @IDCTPN
END

GO
EXECUTE SUACTPHIEUNHAP @IDCTPN='CTPN002', @IDPN='PN002', @IDSP ='SP002', @GIA='2000000', @SOLUONGNHAP='100', @THANHTIEN='200000000'
GO

--14. sửa ct hóa đơn
GO 
CREATE PROC SUACTHOADON (@IDCTHD char(10), @IDHD char(10), @IDSP char(10), @GIA money, @SOLUONG int)
AS
BEGIN
	UPDATE CTHOADON
	SET	IDHD = @IDHD, IDSP = @IDSP, GIA = @GIA, SOLUONG = @SOLUONG
	WHERE IDCTHD = @IDCTHD
END

GO
EXECUTE SUACTHOADON @IDCTHD='CTHD005', @IDHD='HD005', @IDSP='SP001', @GIA='10000000', @SOLUONG='10'
GO


--15 . sửa thông số
GO 
CREATE PROC SUACTTHONGSO (@IDCTTS char(10), @IDSP char(10), @IDTS char(10), @GIATRITS nvarchar(50))
AS
BEGIN
	UPDATE CTTHONGSO
	SET	IDSP = @IDSP, IDTS = @IDTS, GIATRITS = @GIATRITS
	WHERE IDCTTS = @IDCTTS
END

GO
EXECUTE SUACTTHONGSO @IDCTTS='CTTS005', @IDSP='SP001', @IDTS='TS001', @GIATRITS=N'thông số này không có giá trị'
go

--thủ tục xóa
--1.xóa khách hàng
go
CREATE PROC  XOAKHACHANG(@IDKH char(10) )
AS
BEGIN
	DELETE FROM KHACHHANG Where (IDKH=@IDKH)
END
go
execute XOAKHACHANG @IDKH=''
go	

--2.xóa quyền
go
CREATE PROC  XOAQUYEN(@IDQUYEN char(10) )
AS
BEGIN
	DELETE FROM QUYEN Where (IDQUYEN=@IDQUYEN)
END
go
execute XOAQUYEN @IDQUYEN=''
go	

--3.xóa thông số
go
CREATE PROC  XOATHONGSO(@IDTS char(10)  )
AS
BEGIN
	DELETE FROM THONGSO Where (IDTS=@IDTS)
END
go
execute XOATHONGSO @IDTS=''
go	

--4.xóa nhà cung cấp
go
CREATE PROC  XOANHACUNGCAP(@IDNCC char(10) )
AS
BEGIN
	DELETE FROM NHACUNGCAP Where (IDNCC=@IDNCC)
END
go
execute XOANHACUNGCAP @IDNCC=''
go	
--5. xóa nhà sản xuất
CREATE PROC XOANHASANXUAT(@IDNSX varchar(10))
AS
BEGIN
	DELETE FROM NHASANXUAT Where (IDNSX= @IDNSX)
END
go
execute XOANHASANXUAT @IDNSX= ''
go

--6. xóa loại sản phẩm
CREATE PROC XOALOAISANPHAM(@IDLOAISP varchar(10))
AS
BEGIN
	DELETE FROM LOAISANPHAM Where (IDLOAISP= @IDLOAISP)
END
go
execute XOALOAISANPHAM @IDLOAISP= ''
go


--7. xóa người dùng
CREATE PROC XOANGUOIDUNG (@IDND varchar(10))
AS
BEGIN
	DELETE FROM NGUOIDUNG Where (IDND= @IDND)
END
go
execute XOANGUOIDUNG @IDND= ''
go
--8. xóa đặt hàng
CREATE PROC XOADATHANG (@IDDH varchar(10))
AS
BEGIN
	DELETE FROM DATHANG Where (IDDH= @IDDH)
END
go
execute XOADATHANG @IDDH = ''
go

--9. xóa hóa đơn
GO 
CREATE PROC XOAHOADON (@IDHD char(10))
AS
BEGIN
	DELETE FROM HOADON
	WHERE IDHD = @IDHD
END

GO
EXECUTE XOAHOADON @IDHD=''
GO

--10.xóa phiếu nhập
go
CREATE PROC XOAPHIEUNHAP(@IDPHIEUNHAP CHAR(10))
AS
BEGIN
	DELETE FROM PHIEUNHAP Where (IDPHIEUNHAP= @IDPHIEUNHAP)
END
go
execute XOAPHIEUNHAP @IDPHIEUNHAP= ''
go
--11.xóa sản phẩm
go
CREATE PROC XOASANPHAM(@IDSP CHAR(10))
AS
BEGIN
	DELETE FROM SANPHAM Where (IDSP= @IDSP)
END
go
execute XOASANPHAM  @IDSP= ''
go


--12.xóa ct đặt hàng

go
CREATE PROC XOACTDATHANG(@IDCTDH CHAR(10))
AS
BEGIN
	DELETE FROM CTDATHANG Where (IDCTDH= @IDCTDH)
END
go
execute XOACTDATHANG  @IDCTDH= ''
go

-- 13. xóa phiếu nhập
GO 
CREATE PROC XOACTPHIEUNHAP (@IDCTPN char(10))
AS
BEGIN
	DELETE FROM CTPHIEUNHAP
	WHERE IDCTPN = @IDCTPN
END

GO
EXECUTE XOACTPHIEUNHAP @IDCTPN=''
GO
--14. xóa ct hóa đơn
GO 
CREATE PROC XOACTHOADON (@IDCTHD char(10))
AS
BEGIN
	DELETE FROM CTHOADON
	WHERE IDCTHD = @IDCTHD
END

GO
EXECUTE XOACTHOADON @IDCTHD=''
GO


--15 . xóa thông số
GO 
CREATE PROC XOACTTHONGSO (@IDCTTS char(10))
AS
BEGIN
	DELETE FROM CTTHONGSO
	WHERE IDCTTS = @IDCTTS
END

GO
EXECUTE XOACTTHONGSO @IDCTTS=''
GO

--thủ tục tìm


--1.tìm kh
Go
Create proc TIMKHACHHANG( @IDKH char(10))
as
begin
select * from KHACHHANG
where @IDKH=IDKH
End
Execute TIMKHACHHANG @IDKH=''
go
--2 tìm quyền
Go
Create proc TIMQUYEN( @IDQUYEN char(10))
as
begin
select * from QUYEN
where @IDQUYEN=IDQUYEN
End
Execute TIMQUYEN @IDQUYEN=''
go
--3.tìm thông số
Go
Create proc TIMTHONGSO( @IDTS char(10))
as
begin
select * from THONGSO
where @IDTS=IDTS
End
Execute TIMTHONGSO @IDTS=''
go
--4.tìm nhà cung cấp
Go
Create proc TIMNHACUNGCAP( @IDNCC CHAR(10))
as
begin
select * from NHACUNGCAP
where @IDNCC=IDNCC
End
Execute TIMNHACUNGCAP @IDNCC=''
go

--5. tìm nhà sản xuất
CREATE PROC TIMNHASANXUAT(@IDNSX varchar(10))
AS
BEGIN
	SELECT *FROM NHASANXUAT
	WHERE IDNSX = @IDNSX
END
go




--6. tìm loại sp
CREATE PROC TIMLOAISANPHAM(@IDLOAISP varchar(10))
AS
BEGIN
	DELETE FROM LOAISANPHAM Where (IDLOAISP= @IDLOAISP)
END
go
execute TIMLOAISANPHAM @IDLOAISP= ''
go



--7. tìm người dùng
CREATE PROC TIMNGUOIDUNG(@IDND varchar(10))
AS
BEGIN
	DELETE FROM NGUOIDUNG Where (IDND= @IDND)
END
go
execute TIMNGUOIDUNG @IDND= ''
go






--8. tìm đặt hàng
CREATE PROC TIMDATHANG(@IDDH varchar(10))
AS
BEGIN
	DELETE FROM DATHANG Where (IDDH= @IDDH)
END
go
execute TIMDATHANG @IDDH= ''
go

--9. tìm hóa đơn
GO 
CREATE PROC TIMHOADON (@IDHD char(10))
AS
BEGIN
	SELECT*FROM HOADON
	WHERE IDHD = @IDHD
END

 

--10.tìm phiếu nhập
GO
CREATE PROC TIMPHIEUNHAP(@IDPHIEUNHAP CHAR(10))
AS
BEGIN
	SELECT *FROM PHIEUNHAP WHERE IDPHIEUNHAP=@IDPHIEUNHAP
END

--11.tìm sản phẩm
GO
CREATE PROC TIMSANPHAM(@IDSP CHAR(10))
AS
BEGIN
	SELECT *FROM SANPHAM WHERE IDSP=@IDSP
END
--12.tìm ct đặt hàng
GO
CREATE PROC TIMCTDATHANG(@IDCTDH CHAR(10))
AS
BEGIN
	SELECT *FROM CTDATHANG WHERE IDCTDH=@IDCTDH
END
GO 



--13. tìm phiếu nhập
GO 
CREATE PROC TIMCTPHIEUNHAP (@IDCTPN char(10))
AS
BEGIN
	SELECT*FROM CTPHIEUNHAP
	WHERE IDCTPN = @IDCTPN
END



-- 14. tìm hóa đơn
GO 
CREATE PROC TIMCTHOADON (@IDCTHD char(10))
AS
BEGIN
	SELECT*FROM CTHOADON
	WHERE IDCTHD = @IDCTHD
END




--15 . tìm thông số
GO 
CREATE PROC TIMCTTHONGSO (@IDCTTS char(10))
AS
BEGIN
	SELECT*FROM CTTHONGSO
	WHERE IDCTTS = @IDCTTS
END